### ISSUE TITLE
Can't push a view controller after an interactive dismissal

### ISSUE THREAD

**Issue by jdisho** [jdisho/Papr#77]
After interactively dismissing `PhotoDetailsViewController`, pushing another view controller does not work. This bug was  introduced in #72 @vaderdan.

**Comment by vaderdan** [comment]
I'll check it today, I managed to reproduce it but it does not happen on certain actions, but on random.
I think it's because the observable is disposed when it shouldn't

**Comment by vaderdan** [comment]
@jdisho the bug should be reproduced by:
open the app
tap on photo (show details controller)
click on close photo
then tap on profile image top left

It also happen prior the pull with gestures and is caused because the SceneCoordinator.actualViewController logic (when dismiss PhotoDetailsController, current controller should be HomeViewController, but it's Papr.HomeViewController) I'll try to fix it in https://github.com/jdisho/Papr/pull/78
